### ISSUE TITLE
st_transform throws IllegalArgumentException

### ISSUE THREAD

**Issue by yavgenypatent** [databrickslabs/mosaic#142]
**Describe the bug**

**To Reproduce**
i have a data set with polygons coordinates, using srid 4326, like this one:

`{"type_id": 5, "srid": 4326, "boundary": [[[37.3525154229526, -121.928194439798], [37.3525844570751, -121.928137522154], [37.3525832392068, -121.928135032693], [37.3525142050844, -121.928191950336], [37.3525154229526, -121.928194439798]]], "holes": [[]]}`

I am trying to transform them to srid 3857, and getting the error mentioned in the title of the issue.

Anything I miss on my end?

stack trace:
`java.lang.IllegalArgumentException
	at com.esri.core.geometry.MultiVertexGeometryImpl.setPointByVal(MultiVertexGeometryImpl.java:196)
	at com.esri.core.geometry.MultiPathImpl._beforeNewSegment(MultiPathImpl.java:217)
	at com.esri.core.geometry.MultiPathImpl.lineTo(MultiPathImpl.java:234)
	at com.esri.core.geometry.MultiPath.lineTo(MultiPath.java:589)
	at com.databricks.labs.mosaic.core.geometry.multilinestring.MosaicMultiLineStringESRI$.$anonfun$createPolyline$1(MosaicMultiLineStringESRI.scala:75)
	at com.databricks.labs.mosaic.core.geometry.multilinestring.MosaicMultiLineStringESRI$.$anonfun$createPolyline$1$adapted(MosaicMultiLineStringESRI.scala:75)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at com.databricks.labs.mosaic.core.geometry.multilinestring.MosaicMultiLineStringESRI$.addPath$1(MosaicMultiLineStringESRI.scala:75)`

**Comment by sllynn** [comment]
Can you share the statement you're running?

**Comment by yavgenypatent** [comment]
sure
`%sql
select st_transform(location_geo, 3857) from site_products_with_location_geo
limit 10`
this is the sql query, the data in the location_geo column is similar to what i pasted in my first post

**Comment by sllynn** [comment]
Those y-coordinates are outside of the range described by EPSG:4326 (-90° to +90°). How are you generating that initial polygon?

**Comment by sllynn** [comment]
Thanks for the link. I'll confess that was news to me.

In which case, I think the sensible thing would be to add an expression that will flip coordinates for a given geometry.

**Comment by yavgenypatent** [comment]
yeah it might be an easy solution, considering most of the libraries tend to not handle this, if i understand correctly.
