### ISSUE TITLE
Getting error while using %%mosaic_kepler.  Error -> py4j.Py4JException: Method st_centroid([class org.apache.spark.sql.Column]) does not exist

### ISSUE THREAD

**Issue by SukhdevKanzariya** [databrickslabs/mosaic#324]
**Describe the bug**
Getting error while using %%mosaic_kepler.  Error -> py4j.Py4JException: Method st_centroid([class org.apache.spark.sql.Column]) does not exist

**To Reproduce**

1) Create notebook as below,

**cmd 1**
%pip install databricks-mosaic --quiet

**cmd 2**
from pyspark.sql.functions import *
import mosaic as mos
mos.enable_mosaic(spark, dbutils)

**cmd 3**
import requests
req = requests.get('https://data.cityofnewyork.us/api/geospatial/d3c5-ddgc?method=export&format=GeoJSON')
with open('/dbfs/tmp/nyc_taxi_zones.geojson', 'wb') as f:
    f.write(req.content)

**cmd 4**

neighbourhoods = (
  spark.read
    .option("multiline", "true")
    .format("json")
    .load("dbfs:/tmp/nyc_taxi_zones.geojson")
    .select("type", explode(col("features")).alias("feature"))
    .select("type", col("feature.properties").alias("properties"), to_json(col("feature.geometry")).alias("geom_json"))
    .withColumn("geom_internal", mos.st_geomfromgeojson("geom_json"))
    .withColumn("geom_wkt", mos.st_aswkt(col("geom_internal")))
    .withColumn("geom_wkb", mos.st_aswkb(col("geom_internal")))
   .limit(1)
)

neighbourhoods.show()

**cmd 5**

%%mosaic_kepler
neighbourhoods "geom_internal" "geometry"

**Expected behavior**
It should show the kepler visualizer and show the geometry on the map

**Screenshots**
![image](https://user-images.githubusercontent.com/128574763/226830456-7333f8d8-0da6-4415-a560-d74a26af1bea.png)
![image](https://user-images.githubusercontent.com/128574763/226830608-730967ec-e05f-495c-93d5-20d3f5a3970d.png)

**Additional context**
It was working few days ago but it seems there are few recent commits around st_centroid as below, which may cause this issue..

https://github.com/databrickslabs/mosaic/commit/63b3e34f47c4db7854ea18e8169cd3d5f971b67c
![image](https://user-images.githubusercontent.com/128574763/226831127-f4d28915-4506-41b5-b33e-791e28245c41.png)

**Comment by milos-colic** [comment]
@SukhdevKanzariya thank you for reporting this issue. 
I have tried to reproduce it but couldnt.
Could you confirm for me that:
- You are running on DBR 11.x+
- Which version of mosaic you are running (latest is 0.3.8)

**Comment by SukhdevKanzariya** [comment]
@milos-colic thank you for checking and replying..

- Databricks runtime version is 11.3 LTS (includes Apache Spark 3.3.0, Scala 2.12)
- yes, i am using mosaic version is 0.3.8

Please suggest if i am missing anything..

**Comment by milos-colic** [comment]
0.3.8 adds GDAL and OGR IO operations.
If that capability is of interest, then I suggest waiting for 0.3.9 where the above issue will be addressed.

**Comment by milos-colic** [comment]
@SukhdevKanzariya I have tried to replicate again on a fresh cluster with the specification above and the issue doesnt happen on 0.3.8 either. Could you please try it on a fresh cluster?

**Comment by hopitas** [comment]
I can confirm that I have similar issues. Tried with new cluster and mosaic 0.3.7 and 0.3.8.


java.lang.NoSuchMethodError: com.esri.core.geometry.ogc.OGCGeometry.centroid()Lcom/esri/core/geometry/ogc/OGCGeometry;
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-2278416192352589> in <module>
----> 1 get_ipython().run_cell_magic('mosaic_kepler', '', 'neighbourhoods "geom_internal" "geometry"\n')

/local_disk0/.ephemeral_nfs/envs/pythonEnv-a791682e-9f07-48ef-aba0-60dc9522c1a6/lib/python3.9/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2397             with self.builtin_trap:
   2398                 args = (magic_arg_s, cell)
-> 2399                 result = fn(*args, **kwargs)
   2400             return result
   2401 

/databricks/python/lib/python3.9/site-packages/decorator.py in fun(*args, **kw)
    230             if not kwsyntax:
    231                 args, kw = fix(args, kw, sig)
--> 232             return caller(func, *(extras + args), **kw)
    233     fun.__name__ = func.__name__
    234     fun.__doc__ = func.__doc__

/local_disk0/.ephemeral_nfs/envs/pythonEnv-a791682e-9f07-48ef-aba0-60dc9522c1a6/lib/python3.9/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/local_disk0/.ephemeral_nfs/envs/pythonEnv-a791682e-9f07-48ef-aba0-60dc9522c1a6/lib/python3.9/site-packages/mosaic/utils/kepler_magic.py in mosaic_kepler(self, *args)
    243         pandas_data = data.limit(limit_ctn).toPandas()
    244 
--> 245         self.set_centroid(pandas_data, feature_type, feature_name)
    246 
    247         m1 = KeplerGl(config=mosaic_kepler_config)

/local_disk0/.ephemeral_nfs/envs/pythonEnv-a791682e-9f07-48ef-aba0-60dc9522c1a6/lib/python3.9/site-packages/mosaic/utils/kepler_magic.py in set_centroid(pandas_data, feature_type, feature_name)
    142 
    143         centroid = (
--> 144             tmp_sdf.select(st_centroid2D(feature_name))
    145             .limit(1)
    146             .collect()[0][0]

/databricks/spark/python/pyspark/instrumentation_utils.py in wrapper(*args, **kwargs)
     46             start = time.perf_counter()
     47             try:
---> 48                 res = func(*args, **kwargs)
     49                 logger.log_success(
     50                     module_name, class_name, function_name, time.perf_counter() - start, signature

/databricks/spark/python/pyspark/sql/dataframe.py in collect(self)
    835         # Default path used in OSS Spark / for non-DF-ACL clusters:
    836         with SCCallSiteSync(self._sc):
--> 837             sock_info = self._jdf.collectToPython()
    838         return list(_load_from_socket(sock_info, BatchedSerializer(CPickleSerializer())))
    839 

/databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1319 
   1320         answer = self.gateway_client.send_command(command)
-> 1321         return_value = get_return_value(
   1322             answer, self.gateway_client, self.target_id, self.name)
   1323 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    194     def deco(*a: Any, **kw: Any) -> Any:
    195         try:
--> 196             return f(*a, **kw)
    197         except Py4JJavaError as e:
    198             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o567.collectToPython.
: java.lang.NoSuchMethodError: com.esri.core.geometry.ogc.OGCGeometry.centroid()Lcom/esri/core/geometry/ogc/OGCGeometry;
	at com.databricks.labs.mosaic.core.geometry.MosaicGeometryESRI.getCentroid(MosaicGeometryESRI.scala:62)
	at com.databricks.labs.mosaic.expressions.geometry.ST_Centroid.nullSafeEval(ST_Centroid.scala:33)
	at org.apache.spark.sql.catalyst.expressions.UnaryExpression.eval(Expression.scala:671)
	at org.apache.spark.sql.catalyst.expressions.Alias.eval(namedExpressions.scala:160)
	at org.apache.spark.sql.catalyst.expressions.InterpretedMutableProjection.apply(InterpretedMutableProjection.scala:101)
	at org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation$$anonfun$apply$42.$anonfun$applyOrElse$82(Optimizer.scala:2384)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation$$anonfun$apply$42.applyOrElse(Optimizer.scala:2384)
	at org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation$$anonfun$apply$42.applyOrElse(Optimizer.scala:2379)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:512)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:99)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:512)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:298)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:294)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$3(TreeNode.scala:517)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1174)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren$(TreeNode.scala:1173)
	at org.apache.spark.sql.catalyst.plans.logical.OrderPreservingUnaryNode.mapChildren(LogicalPlan.scala:274)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:517)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:298)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:294)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$3(TreeNode.scala:517)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1174)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren$(TreeNode.scala:1173)
	at org.apache.spark.sql.catalyst.plans.logical.GlobalLimit.mapChildren(basicLogicalOperators.scala:1664)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:517)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:298)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:294)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformWithPruning(TreeNode.scala:478)
	at org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation$.apply(Optimizer.scala:2379)
	at org.apache.spark.sql.catalyst.optimizer.ConvertToLocalRelation$.apply(Optimizer.scala:2377)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$3(RuleExecutor.scala:216)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:216)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:38)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:213)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:205)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:205)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:184)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:153)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:184)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$optimizedPlan$1(QueryExecution.scala:266)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:319)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$3(QueryExecution.scala:337)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:763)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:337)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:985)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:334)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:262)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:258)
	at org.apache.spark.sql.execution.QueryExecution.assertOptimized(QueryExecution.scala:276)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:295)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:292)
	at com.databricks.sql.transaction.tahoe.metering.DeltaMetering$.reportUsage(DeltaMetering.scala:202)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:309)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:392)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:188)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:985)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:142)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:342)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:4290)
	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:4050)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
	at java.lang.Thread.run(Thread.java:750)

**Comment by SukhdevKanzariya** [comment]
@milos-colic 

I just tried it on fresh cluster and again getting the same issue on mosaic 0.3.8. attaching few snapshots of my notebook. please do let me know if i am missing anything. I have to use mosaic 0.3.8 as I am working on raster file which have a GDAL dependency.

![image](https://user-images.githubusercontent.com/128574763/227107530-08e98e06-7bbc-496e-b974-4e74d0cf75dd.png)
![image](https://user-images.githubusercontent.com/128574763/227107693-e9c40589-418e-4846-8f9e-51ca0c49cf6f.png)
![image](https://user-images.githubusercontent.com/128574763/227107787-582482ea-c794-4c42-beea-53894ede02e9.png)

@mjohns-databricks

**Comment by hopitas** [comment]
I found the reason for my error. It was conflicting library from: https://developers.arcgis.com/geoanalytics/install/databricks/azure/

I managed to install ghe geoanalytics libraries globally, even though my intention was to install them only locally. This resulted the conflict even when I ran fresh cluster with mosaic.

**Comment by SukhdevKanzariya** [comment]
@milos-colic 
i am using mosaic version 0.3.9 now. and i am not facing above issue on it. Thank you :)
