### ISSUE TITLE
Custom Grid not working (python)

### ISSUE THREAD

**Issue by prinsniels** [databrickslabs/mosaic#325]
**Describe the bug**
When trying to use the newly added custom grid index system, the lib throws a `java.lang.Error: Index not supported yet!`

**To Reproduce**
Shortest reproduction example;

```python
%pip install databricks-mosaic --quiet
```

```python
import mosaic as mos
import pyspark.sql.functions as F

mos.__version__

Out[0]: '0.3.8'
```

```python
spark.conf.set("spark.databricks.labs.mosaic.index.system", "CUSTOM(-180,180,-180,180,2,30,30)")
mos.enable_mosaic(spark, dbutils)

df = spark.createDataFrame([{
    'wkt': 'MULTIPOLYGON (((30 20, 45 40, 10 40, 30 20)), ((15 5, 40 10, 10 20, 5 10, 15 5)))'
    }])

df.select(mos.grid_polyfill('wkt', F.lit(0))).show(1, False)

res => java.lang.Error: Index not supported yet!
```

**Expected behavior**
Ability to use custom indexing, so that I can avoid the costly projection transformation.

**stack**
```
Py4JJavaError: An error occurred while calling o3803.grid_polyfill.
: java.lang.Error: Index not supported yet!
	at com.databricks.labs.mosaic.core.index.IndexSystemID$.apply(IndexSystemID.scala:13)
	at com.databricks.labs.mosaic.expressions.index.Polyfill.<init>(Polyfill.scala:26)
	at com.databricks.labs.mosaic.functions.MosaicContext$functions$.grid_polyfill(MosaicContext.scala:795)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by prinsniels** [comment]
Nevermind. There was an old mosaic scala version installed on the cluster
