### ISSUE TITLE
BNG and KRings don't play nicely at the edges

### ISSUE THREAD

**Issue by tompeterken-os** [databrickslabs/mosaic#354]
**Describe the bug**
The in-built [letterMap](https://github.com/databrickslabs/mosaic/blob/a5b72b737e32518fbe4d64179dec43a7ee9eba33/src/main/scala/com/databricks/labs/mosaic/core/index/BNGIndexSystem.scala#L85) of OS [BNG grid squares](https://en.wikipedia.org/wiki/Ordnance_Survey_National_Grid#/media/File:British_National_Grid.svg) covers all of GB, but doesn't include a buffer.  Using mosaic's grid_cellkring and grid_cellkloop functions with either
- a sufficiently large value of k, or
- on grid cells near the edge

causes grid cells outside of the letterMap to be requested, resulting in an IndexOutOfBoundsException.

**To Reproduce**
```
import mosaic as mos
from pyspark.sql import functions as F

# Use BNG indexing
spark.conf.set('spark.databricks.labs.mosaic.index.system', 'BNG')
mos.enable_mosaic(spark, dbutils)

df = (
  spark.createDataFrame([{'bng': 'TM99'}])
  .withColumn('kring', mos.grid_cellkring('bng', F.lit(1)))
)

df.display()
```

Results in the following.  I've only included a small sample of the traceback, happy to provide the full if it's useful.

```
IndexOutOfBoundsException: 7
  ...
	at com.databricks.labs.mosaic.core.index.BNGIndexSystem$.format(BNGIndexSystem.scala:121)
	at com.databricks.labs.mosaic.core.index.IndexSystem.serializeCellId(IndexSystem.scala:42)
	at com.databricks.labs.mosaic.expressions.index.CellKRing.$anonfun$nullSafeEval$1(CellKRing.scala:69)
	at scala.collection.immutable.List.map(List.scala:297)
	at com.databricks.labs.mosaic.expressions.index.CellKRing.nullSafeEval(CellKRing.scala:69)
  ...
```

**Expected behavior**
I think there's arguments for either of the following, and I think either would be fine:
1. Extend the letterMap by a buffer tile in every direction, so the above example would return cells in the (fictional) TN square.
2. Only return valid cells, so the above example would only return the 6 cells of the kring's usual 9 which fall within the TM square.

**Comment by milos-colic** [comment]
@tompeterken-os Thank you for reporting this, indeed I beleive there is a check missing in case we step outside of the grid. The KRing and KLoop concepts are borrowed from H3 which is a continuous grid and BNG is a finite grid.
I believe the option 2 is the correct way to go. We dont want to step outside of the grid in that case sicne we use KRings to define neighbourhoods and the assumption is no other data should be outside of the grid anyhow.
I will open a PR for this tomorrow, the fix should be straightforward.

**Comment by tompeterken-os** [comment]
Thanks Milos!  I wasn't sure which of the two options would be easiest to implement, but that sounds great.

**Comment by milos-colic** [comment]
@tompeterken-os I have opened a PR for the fix for this, along with other few fixes for BNG it will be available in the next release (0.3.10+).
I have fixed the isValid function in BNG index system. It wasn't checking correctly for non-existing letters, now it does.
